name: weather_built_by_flutter
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  fluro: ^1.3.4
  http: ^0.12.0+2
  event_bus: ^1.0.1
  shared_preferences: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - image/first_page.jpg
    - image/second_page.jpg
    - image/flutter_logo.png
    - image/0.png
    - image/1.png
    - image/2.png
    - image/3.png
    - image/4.png
    - image/5.png
    - image/6.png
    - image/7.png
    - image/8.png
    - image/9.png
    - image/10.png
    - image/11.png
    - image/12.png
    - image/13.png
    - image/14.png
    - image/15.png
    - image/16.png
    - image/17.png
    - image/18.png
    - image/19.png
    - image/20.png
    - image/21.png
    - image/22.png
    - image/23.png
    - image/24.png
    - image/25.png
    - image/26.png
    - image/27.png
    - image/28.png
    - image/29.png
    - image/30.png
    - image/31.png
    - image/32.png
    - image/39.png
    - image/49.png
    - image/53.png
    - image/54.png
    - image/55.png
    - image/56.png
    - image/57.png
    - image/58.png
    - image/99.png
    - image/301.png
    - image/302.png
    - json/city.json
    - json/weather_default.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
